### ISSUE TITLE
Settings for main example

### ISSUE THREAD

**Issue by vgoklani** [iArunava/Style-Transfer-with-PyTorch#1]
Hey there - thanks for posting your code, it's very helpful for learning!

Could you please post the settings you used to generate the main example. I tried using both your content and style image, but the output doesn't look at saturated as your generated image.

Thanks!

**Comment by iArunava** [comment]
I don't remember for exact. But I think the hyperparameters were pretty same. Except that the size of the image it is resized to was quire larger as I training on a GPU.
So, just wait, I will make some changes so that you can include the size your image it is resized to.
For now, it is `500`, I used something around `1000`
